selection:
  save_to_clipboard: true

mouse:
  hide_when_typing: true

window:
  padding:
    x: 5
    y: 0

font:
  normal:
    family: Hack
  size: 10

# To find a the decimal value for a scancode use
# `sudo showkey` and type the char you want
key_bindings:
  # Sends byte sequence expected by vim to understand those key bindings
  - { key: Return, mods: Shift, chars: "\x1b[13;2u" }
  - { key: Return, mods: Control, chars: "\x1b[13;5u" }

  # Override some mappings for azerty keyboards
  - { key: Slash, mods: Shift, mode: Vi|~Search, action: SearchForward }
  # ,
  - { key: 50, mods: Shift, mode: Vi|~Search, action: SearchBackward }

  # Number keys are always off because we need to press shift
  - { key: Key0, mods: Shift, mode: Vi|~Search, action: First }
  # $
  - { key: 27, mode: Vi|~Search, action: Last }
  # ^ - still not working: https://github.com/alacritty/alacritty/issues/5181
  # Waiting for this issue to be solved: https://github.com/rust-windowing/winit/issues/753
  # - { key: Caret, mode: Vi|~Search, action: FirstOccupied }
  # - { key: 26, mode: Vi|~Search, action: FirstOccupied }
  # %
  - { key: 40, mods: Shift, mode: Vi|~Search, action: Bracket }

  - { key: Equals, mods: Control, action: ResetFontSize }
  # = (Equals does not work with Control|Shift ...)
  - { key: 13, mods: Control|Shift, action: IncreaseFontSize }

# vim: ts=2 sw=2 et
