window:
  padding:
    x: 2
    y: 0

font:
  normal:
    family: Hack Nerd Font Mono
  size: 7

key_bindings:
  # To enable <C-Enter> and <S-Enter> in vim
  - { key: Return,  mods: Shift,                         chars: "\x1b[13;2u"              }
  - { key: Return,  mods: Control,                       chars: "\x1b[13;5u"              }
